'use client';

import React from 'react';

export default function Home() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Space+Grotesk:wght@500;600;700&display=swap');
:root{--bg:#050909;--panel:#0b1211;--panel2:#0e1715;--text:#f7f9f8;--muted:#9caeaa;--teal:#62d2c5;--line:rgba(98,210,197,.24);--white:#fff;--max:1180px}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif;line-height:1.55;overflow-x:hidden}
a{color:inherit;text-decoration:none}button{font:inherit}
body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 75% 15%,rgba(98,210,197,.10),transparent 30%),radial-gradient(circle at 10% 50%,rgba(98,210,197,.05),transparent 25%);z-index:-1}
.container{width:min(var(--max),calc(100% - 44px));margin:auto}
.nav{position:fixed;top:0;left:0;right:0;z-index:50;background:rgba(5,9,9,.72);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.05)}
.nav-inner{height:78px;display:flex;align-items:center;justify-content:space-between}
.brand{display:flex;align-items:center;gap:12px;font-weight:900;letter-spacing:2px}.brand img{width:42px;height:30px;object-fit:cover;border-radius:5px}.brand span{font-size:18px}.navlinks{display:flex;gap:28px;color:#b7c4c1;font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px}.navlinks a:hover{color:var(--teal)}
.menu{display:none;border:0;background:none;color:white;font-size:30px}
.hero{min-height:100vh;padding:128px 0 70px;display:grid;align-items:center;position:relative}
.hero-grid{display:grid;grid-template-columns:1.02fr .98fr;gap:64px;align-items:center}
.kicker{display:inline-flex;align-items:center;gap:10px;border:1px solid var(--line);padding:10px 16px;border-radius:999px;color:var(--teal);font-weight:800;font-size:12px;letter-spacing:2px;text-transform:uppercase;background:rgba(98,210,197,.035)}.dot{width:7px;height:7px;border-radius:50%;background:var(--teal);box-shadow:0 0 18px var(--teal)}
.hero h1{font-family:'Space Grotesk',Inter,sans-serif;font-size:clamp(50px,7vw,94px);line-height:.92;letter-spacing:-4px;margin:28px 0 22px;text-transform:uppercase}.hero h1 .teal{color:var(--teal)}
.hero p{color:var(--muted);font-size:18px;max-width:650px}.actions{display:flex;gap:12px;margin-top:30px;flex-wrap:wrap}.btn{padding:14px 20px;border-radius:12px;border:1px solid var(--line);font-weight:800;font-size:14px;display:inline-flex;align-items:center;gap:9px;transition:.2s}.btn.primary{background:var(--teal);color:#03100e;border-color:var(--teal)}.btn:hover{transform:translateY(-2px)}
.hero-brand{min-height:540px;border:1px solid rgba(98,210,197,.18);border-radius:30px;background:linear-gradient(145deg,#07100e,#0d1715);display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden;box-shadow:0 35px 100px rgba(0,0,0,.35)}
.hero-brand:before{content:"";position:absolute;width:440px;height:440px;border:1px solid rgba(98,210,197,.18);border-radius:50%;box-shadow:0 0 0 50px rgba(98,210,197,.025),0 0 0 100px rgba(98,210,197,.018)}
.brand-stack{position:relative;text-align:center;z-index:2}.logo-tile{width:154px;height:108px;object-fit:cover;border-radius:12px;margin:auto;box-shadow:0 18px 45px rgba(0,0,0,.35);border:1px solid rgba(255,255,255,.08)}.brand-stack h2{font-family:'Space Grotesk';font-size:68px;letter-spacing:-4px;margin-top:22px}.brand-stack .meaning{letter-spacing:7px;font-size:11px;font-weight:800;color:#c6d2cf;margin-top:3px}.brand-stack .tag{margin-top:20px;color:var(--teal);font-weight:700;letter-spacing:2px;text-transform:uppercase;font-size:12px}
.section{padding:110px 0}.section.alt{background:#070d0c;border-block:1px solid rgba(255,255,255,.04)}.eyebrow{color:var(--teal);font-weight:900;letter-spacing:3px;text-transform:uppercase;font-size:12px;margin-bottom:15px}.section h2{font-family:'Space Grotesk';font-size:clamp(38px,5vw,66px);line-height:1;letter-spacing:-3px;max-width:800px}.lead{color:var(--muted);max-width:700px;font-size:17px;margin-top:18px}
.promise{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:46px}.promise-card{padding:34px;border:1px solid rgba(98,210,197,.16);border-radius:22px;background:linear-gradient(145deg,#0a1211,#0c1513)}.promise-card h3{font-size:26px;margin-bottom:10px}.promise-card p{color:var(--muted)}
.services{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:45px}.service{min-height:210px;padding:24px;border:1px solid rgba(255,255,255,.07);border-radius:18px;background:#0a100f}.num{font-size:12px;color:var(--teal);font-weight:900;letter-spacing:2px}.service h3{margin:26px 0 9px;font-size:20px}.service p{color:var(--muted);font-size:14px}
.process{margin-top:45px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.step{padding:22px;border-top:1px solid var(--line)}.step b{color:var(--teal);font-size:13px}.step h3{margin-top:10px;font-size:18px}.step p{color:var(--muted);font-size:14px;margin-top:8px}
.team-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:22px;margin-top:48px}.team-main,.founder{border:1px solid rgba(98,210,197,.15);border-radius:24px;background:#0a1211;padding:34px}.team-main h3,.founder h3{font-size:28px;margin-bottom:12px}.team-main p,.founder p{color:var(--muted)}.chips{display:flex;gap:9px;flex-wrap:wrap;margin-top:24px}.chip{padding:9px 12px;border-radius:999px;background:#101b19;border:1px solid rgba(255,255,255,.07);font-size:12px;color:#d5dfdd;font-weight:700}
.social-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:45px}.social-card{padding:26px;border-radius:20px;border:1px solid rgba(255,255,255,.07);background:#0a100f}.social-card h3{font-size:20px}.social-card p{color:var(--muted);font-size:14px;margin:7px 0 18px}.socials{display:flex;gap:9px;flex-wrap:wrap}.socials a{border:1px solid rgba(98,210,197,.22);padding:10px 13px;border-radius:10px;font-size:12px;font-weight:800;color:var(--teal)}
.cta{padding:80px 0 100px}.cta-box{border:1px solid var(--line);border-radius:28px;padding:55px;background:radial-gradient(circle at 80% 20%,rgba(98,210,197,.12),transparent 30%),#09110f;display:flex;align-items:center;justify-content:space-between;gap:30px}.cta h2{font-family:'Space Grotesk';font-size:clamp(36px,5vw,60px);line-height:1;letter-spacing:-2px}.cta p{color:var(--muted);margin-top:12px;max-width:580px}
footer{border-top:1px solid rgba(255,255,255,.07);padding:35px 0 50px;color:#82918d;font-size:13px}.footer-grid{display:flex;justify-content:space-between;gap:30px;flex-wrap:wrap}.footer-brand{color:white;font-weight:900;letter-spacing:2px}.smalllinks{display:flex;gap:18px;flex-wrap:wrap}.smalllinks a:hover{color:var(--teal)}
.reveal{animation:up .8s ease both}@keyframes up{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}
@media(max-width:900px){.hero-grid,.team-grid{grid-template-columns:1fr}.services{grid-template-columns:1fr 1fr}.process{grid-template-columns:1fr 1fr}.hero-brand{min-height:430px}.navlinks{display:none}.menu{display:block}}
@media(max-width:620px){.container{width:min(var(--max),calc(100% - 28px))}.hero{padding-top:105px}.hero h1{font-size:52px;letter-spacing:-2.5px}.brand-stack h2{font-size:50px}.services,.process,.promise,.social-grid{grid-template-columns:1fr}.cta-box{padding:34px;display:block}.cta .btn{margin-top:22px}.section{padding:80px 0}}

.plans-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:46px;align-items:stretch}
.plan-card{border:1px solid rgba(255,255,255,.08);border-radius:22px;background:linear-gradient(180deg,#0a1312 0%,#060b0a 100%);padding:36px 24px 28px;display:flex;flex-direction:column;justify-content:space-between;position:relative;transition:.3s}
.plan-card:hover{transform:translateY(-4px);border-color:rgba(98,210,197,.3);box-shadow:0 18px 45px rgba(0,0,0,.4)}
.plan-card.highlighted{border:1px solid #62d2c5;box-shadow:0 0 35px rgba(98,210,197,.18),0 15px 40px rgba(0,0,0,.45);background:linear-gradient(180deg,#0c1917 0%,#070f0d 100%)}
.plan-popular-tag{position:absolute;top:-13px;left:50%;transform:translateX(-50%);background:#62d2c5;color:#03100e;font-size:10px;font-weight:800;letter-spacing:1.5px;padding:4px 14px;border-radius:999px;text-transform:uppercase;white-space:nowrap;box-shadow:0 0 18px rgba(98,210,197,.5)}
.plan-kicker{font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;color:#7f9591;margin-bottom:12px}
.plan-kicker.teal{color:var(--teal)}
.plan-title{font-family:'Space Grotesk',Inter,sans-serif;font-size:32px;font-weight:700;color:#fff;letter-spacing:-1px;margin-bottom:4px;line-height:1}
.plan-sub{font-size:13.5px;font-weight:600;color:#d5dfdd;margin-bottom:14px}
.plan-desc{font-size:12.5px;color:#8e9f9b;line-height:1.5;margin-bottom:20px;min-height:56px}
.plan-deliverables{font-size:12.5px;font-weight:700;color:#fff;line-height:1.5;padding-bottom:18px;margin-bottom:20px;border-bottom:1px solid rgba(255,255,255,.08)}
.plan-features{list-style:none;margin:0 0 28px 0;padding:0;display:flex;flex-direction:column;gap:12px;flex-grow:1}
.plan-features li{display:flex;align-items:flex-start;gap:9px;font-size:12px;color:#b7c7c3;line-height:1.4}
.plan-features li svg{flex-shrink:0;margin-top:2px}
.plan-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:13px 16px;border-radius:999px;background:rgba(16,26,24,.85);border:1px solid rgba(255,255,255,.12);color:#fff;font-size:11.5px;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;transition:.2s;margin-top:auto;box-shadow:0 4px 15px rgba(0,0,0,.4)}
.plan-btn:hover{background:rgba(98,210,197,.15);border-color:#62d2c5;color:#62d2c5;transform:translateY(-2px)}
.plan-card.highlighted .plan-btn{background:rgba(98,210,197,.14);border-color:rgba(98,210,197,.4);color:#62d2c5}
.plan-card.highlighted .plan-btn:hover{background:#62d2c5;color:#03100e}
@media(max-width:1024px){.plans-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:640px){.plans-grid{grid-template-columns:1fr}}


` }} />
      

<nav className="nav"><div className="container nav-inner"><a className="brand" href="#home"><img src="assets/logo-icon.png" alt="GEN-NETZ logo" /><span>GEN-NETZ</span></a><div className="navlinks"><a href="#what">What We Do</a><a href="#process">Process</a><a href="#plans">Plans</a><a href="#team">Team</a><a href="#socials">Socials</a><a href="#contact">Contact</a></div><button className="menu" aria-label="Menu">☰</button></div></nav>

<main id="home">
<section className="hero"><div className="container"><div className="hero-brand reveal" style={{minHeight: 'auto', padding: '52px 28px', marginBottom: '42px'}}><div className="brand-stack"><img className="logo-tile" src="assets/logo-icon.png" alt="GEN-NETZ logo" /><h2>GEN-NETZ</h2><div className="meaning">NEXTGENERATION NETWORKZ</div><div className="tag">Strategy • Content • Production • Management</div></div></div><div className="hero-grid" style={{gridTemplateColumns: '1fr'}}><div className="reveal" style={{textAlign: 'center', maxWidth: '1050px', margin: 'auto'}}><div className="kicker"><span className="dot"></span> Strategy-led • Content-focused • Business-ready</div><h1>Your Instagram.<br /><span className="teal">Our Responsibility.</span></h1><p style={{margin: 'auto'}}>You focus on your business, brand or creator journey. GEN-NETZ handles the Instagram system behind it — strategy, content, shooting, editing, publishing, community and performance analysis.</p><div className="actions" style={{justifyContent: 'center'}}><a className="btn primary" href="#contact">Start a conversation →</a><a className="btn" href="#what">See what we handle</a></div></div></div></div></section>

<section id="what" className="section alt"><div className="container"><div className="eyebrow">The idea</div><h2>Stop worrying about what to post. Start building a system.</h2><p className="lead">Your account should not depend on random ideas, inconsistent posting or chasing every trend. We build a repeatable content system around your brand, audience and goals.</p><div className="promise"><div className="promise-card"><h3>We don't promise viral numbers.</h3><p>Views, followers and reach can never be guaranteed. Our focus is professional execution, useful content and continuous improvement.</p></div><div className="promise-card"><h3>We build the process behind growth.</h3><p>Research → Strategy → Content → Shooting → Editing → Publishing → Community → Analytics → Improvement.</p></div></div></div></section>

<section className="section"><div className="container"><div className="eyebrow">What we do</div><h2>Everything your Instagram needs, under one roof.</h2><p className="lead">From the first idea to the final report, GEN-NETZ handles the moving parts so you can focus on your business or creator work.</p><div className="services"><div className="service"><span className="num">01 / STRATEGY</span><h3>Research & Strategy</h3><p>Account audit, audience research, competitor research, positioning and content direction.</p></div><div className="service"><span className="num">02 / CONTENT</span><h3>Content Creation</h3><p>Reels, posts, stories, hooks, scripts, captions and content calendars built for your brand.</p></div><div className="service"><span className="num">03 / PRODUCTION</span><h3>Shooting & Editing</h3><p>Professional camera work, creator-led shoots, cinematic edits, motion graphics and covers.</p></div><div className="service"><span className="num">04 / MANAGEMENT</span><h3>Publishing & Analytics</h3><p>Scheduling, publishing, community support, monthly reporting and ongoing improvement.</p></div></div></div></section>

<section id="process" className="section alt"><div className="container"><div className="eyebrow">How GEN-NETZ works</div><h2>A clear process. No confusion.</h2><p className="lead">Every month follows a structured workflow, with approvals and scope kept clear.</p><div className="process"><div className="step"><b>01 — PLAN</b><h3>Research</h3><p>We understand your account, audience, competitors and goals.</p></div><div className="step"><b>02 — CREATE</b><h3>Build the content</h3><p>Ideas, scripts, formats, captions and creative direction are prepared.</p></div><div className="step"><b>03 — PRODUCE</b><h3>Shoot & edit</h3><p>Content is captured by the team or supplied by you, then professionally edited.</p></div><div className="step"><b>04 — PUBLISH</b><h3>Learn & improve</h3><p>Approved content goes live, performance is reviewed and the next cycle improves.</p></div></div></div></section>


<section id="plans" className="section"><div className="container"><div className="eyebrow">01 / Plans</div><h2>Choose Your Level</h2><p className="lead">Four ways to work with GENNETZ &mdash; from complete Instagram responsibility to individual content support.</p><div className="plans-grid">
<div className="plan-card"><div><div className="plan-kicker">FULL PRODUCTION</div><h3 className="plan-title">ELITE</h3><div className="plan-sub">Complete Instagram Management</div><p className="plan-desc">For brands and founders who want me to take primary responsibility for their Instagram content and growth.</p><div className="plan-deliverables">10 Reels/month &bull; 4&ndash;6 Posts/month &bull; 10&ndash;12 Stories/month</div><ul className="plan-features">
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Full production directed &amp; shot by me</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Planned shooting visits included</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Account analysis &amp; competitor research</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Every reel personally edited by Chaithu</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Content planning &amp; scheduled publishing</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Comments &amp; DM management</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Weekly check-ins + monthly reports</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Meta Verified onboarding support</span></li>
</ul></div><a href="https://wa.me/916383884581?text=Hi%20Chaithu,%20I'm%20interested%20in%20the%20Elite%20Plan" target="_blank" className="plan-btn"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg><span>CHOOSE ELITE &rarr;</span></a></div>

<div className="plan-card highlighted"><div className="plan-popular-tag">&#9733; MOST POPULAR</div><div><div className="plan-kicker teal">CONTENT + MANAGEMENT</div><h3 className="plan-title">GROWTH</h3><div className="plan-sub">Collaborative Production</div><p className="plan-desc">For clients who provide regular HD footage while I guide the strategy, edit every piece, and add in-person shoots.</p><div className="plan-deliverables">10 Reels/month &bull; 4&ndash;6 Posts/month &bull; 10&ndash;12 Stories/month</div><ul className="plan-features">
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Client footage + 1&ndash;2 shooting visits/month</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>In-depth research &amp; content strategy</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Professional editing by Chaithu personally</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Content publishing &amp; scheduling</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Comments &amp; DM community management</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Weekly check-in + monthly reports</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Meta Verified onboarding support</span></li>
</ul></div><a href="https://wa.me/916383884581?text=Hi%20Chaithu,%20I'm%20interested%20in%20the%20Growth%20Plan" target="_blank" className="plan-btn"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg><span>CHOOSE GROWTH &rarr;</span></a></div>

<div className="plan-card"><div><div className="plan-kicker">FLEXIBLE</div><h3 className="plan-title">FLEX</h3><div className="plan-sub">Lighter Pacing</div><p className="plan-desc">For brands that want consistent, polished management and active reels with a lighter monthly cadence.</p><div className="plan-deliverables">3&ndash;4 Reels/month &bull; 1&ndash;2 Posts/month &bull; 3&ndash;4 Stories/week</div><ul className="plan-features">
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Client footage + visits (1&ndash;2 every 2 months)</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Research &amp; monthly content strategy</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Every reel personally edited by Chaithu</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Content scheduling &amp; publishing</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Monthly performance review</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Meta Verified onboarding support</span></li>
</ul></div><a href="https://wa.me/916383884581?text=Hi%20Chaithu,%20I'm%20interested%20in%20the%20Flex%20Plan" target="_blank" className="plan-btn"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg><span>CHOOSE FLEX &rarr;</span></a></div>

<div className="plan-card"><div><div className="plan-kicker">NO COMMITMENT</div><h3 className="plan-title">CREATOR</h3><div className="plan-sub">Pay-As-You-Go</div><p className="plan-desc">For creators and businesses wanting high-impact editing or strategy without a monthly retainer.</p><div className="plan-deliverables">Individual deliverables as selected</div><ul className="plan-features">
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Choose what you need (Reels, Posts, Stories)</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Per-service transparent pricing</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Editing-only packages available</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>Shooting visits available (extra charge)</span></li>
<li><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#62d2c5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg><span>1-on-1 Instagram strategy guidance</span></li>
</ul></div><a href="https://wa.me/916383884581?text=Hi%20Chaithu,%20I'd%20like%20to%20discuss%20the%20Pay-As-You-Go%20Creator%20option" target="_blank" className="plan-btn"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg><span>DISCUSS CREATOR &rarr;</span></a></div>
</div></div></section>

<section id="work" className="section alt"><div className="container"><div className="eyebrow">Creative direction</div><h2>Content that looks professional — and has a reason to exist.</h2><p className="lead">GEN-NETZ combines short-form storytelling, visual editing and platform-native content into a consistent brand system.</p><div className="promise" style={{marginTop: '42px'}}><div className="promise-card"><span className="num">REELS</span><h3>Hook → Story → Payoff</h3><p>Fast, clear short-form concepts built around audience attention and the client's message.</p></div><div className="promise-card"><span className="num">BRANDING</span><h3>Consistent visual language</h3><p>Typography, covers, editing style and content pillars work together instead of looking like disconnected posts.</p></div><div className="promise-card"><span className="num">PRODUCTION</span><h3>Camera → Edit → Publish</h3><p>Professional shooting and post-production where included, with clear production scope and approvals.</p></div><div className="promise-card"><span className="num">ANALYTICS</span><h3>Learn from the account</h3><p>Performance is reviewed to understand what deserves more testing and what needs to change.</p></div></div></div></section>

<section id="team" className="section"><div className="container"><div className="eyebrow">People behind GEN-NETZ</div><h2>Experience in the work. Specialists behind every stage.</h2><p className="lead">GEN-NETZ is built around hands-on content and social-media experience — combining strategy, creator experience, production and editing.</p><div className="team-grid"><div className="team-main"><h3>Our experience</h3><p>Founder-led direction supported by a focused creative team. Our capabilities cover the full content pipeline, from camera control and storytelling to professional editing, writing and account management.</p><div className="chips"><span className="chip">100K+ creator audience experience</span><span className="chip">Professional editing</span><span className="chip">Camera & shooting</span><span className="chip">Content writing</span><span className="chip">Instagram strategy</span><span className="chip">Analytics & reporting</span></div></div><div className="founder"><h3>Founder</h3><p><strong style={{color: '#fff'}}>Creator • Strategist • Content Lead</strong></p><p style={{marginTop: '10px'}}>The founder brings first-hand creator experience, including building and managing a 100K+ Instagram audience, while developing GEN-NETZ as a dedicated social-media management company.</p><div className="actions" style={{marginTop: '22px'}}><a className="btn" href="https://www.instagram.com/chaithu.z/" target="_blank">Personal Instagram ↗</a></div></div></div></div></section>

<section id="socials" className="section alt"><div className="container"><div className="eyebrow">Connect</div><h2>Follow the people. Follow the network.</h2><p className="lead">Personal creator profiles and GEN-NETZ company channels can live here. Replace the company placeholders with your final handles before launch.</p><div className="social-grid"><div className="social-card"><h3>Founder / Personal</h3><p>Creator profiles and personal work.</p><div className="socials"><a href="https://www.instagram.com/chaithu.z/" target="_blank">Instagram · @chaithu.z</a><a href="https://www.youtube.com/@chaithu.z" target="_blank">YouTube · @chaithu.z</a><a href="https://www.facebook.com/chaithu" target="_blank">Facebook · @chaithu</a></div></div><div className="social-card"><h3>GEN-NETZ Company</h3><p>Official company presence.</p><div className="socials"><a href="https://www.gennetz.com/" target="_blank">Website · gennetz.com</a><a href="#" >Instagram · Add handle</a><a href="#" >Facebook · Add page</a><a href="#" >YouTube · Add channel</a></div></div></div></div></section>

<section id="contact" className="cta"><div className="container"><div className="cta-box"><div><div className="eyebrow">Ready when you are</div><h2>Your Instagram.<br />Our Responsibility.</h2><p>Tell us what you are building. We'll map the content, production and management support around it.</p></div><div className="actions"><a className="btn primary" href="https://wa.me/916383884581" target="_blank">Chat on WhatsApp →</a><a className="btn" href="mailto:hello@gennetz.com">hello@gennetz.com</a></div></div></div></section>
</main>
<footer><div className="container footer-grid"><div><div className="footer-brand">GEN-NETZ</div><div style={{marginTop: '7px'}}>NEXTGENERATION NETWORKZ</div></div><div className="smalllinks"><a href="#home">Home</a><a href="#what">What We Do</a><a href="#process">Process</a><a href="#plans">Plans</a><a href="#team">Team</a><a href="#socials">Socials</a><a href="#contact">Contact</a></div><div>© 2026 GEN-NETZ. All rights reserved.</div></div></footer>


    </>
  );
}
